#' @title matching.CI  
#'  
#' @description \code{matching.CI} give the estimates of the match episode, using different 
#' estimator or inference.  
#'  
#' @param sets episode generated by match.R
#' @param alpha significance level
#' @param estimand "ATT" or "Dynamic"
#' @param method "Simple DID" now, can be added in later version
#' @param vce "jackknife" or "bootstrap"
#' @param nsim numbers of bootstrap
#'  
#' @return \code{matching.CI} return a dataframe containing the periods, estimates, and the CI
#' @author Hongyi Jiang <hyjiang2017@nsd.pku.edu.cn>
#'  
#' @export
matching.CI <- function(sets, 
                     alpha = 0.05, 
                     estimand = "Dynamic", 
                     method = "Simple DID", 
                     vce = "jackknife", 
                     nsim = 200){
  # get the confidence interval of treatment effect
  
  # sets: a list which contains the wide raw balanced panel, the matrix of match,
  # the true id and time, the uning parameters c, a, b, and each episode/cohort
  # alpha: significance level, 0.05 by default
  # estimand: dynamic by default, can be ATT or dynamic
  # method: jackknife by default, can be bootstrap or jackknife
  # nsim: number of bootstrap, will not be used when method == "jackknife"
  
  ## get the wide panel data
  Ywide <- sets[["wide panel"]][["Ywide"]]
  Dwide <- sets[["wide panel"]][["Dwide"]]
  Xwide <- sets[["wide panel"]][["Xwide"]]
  
  ## get the variable names
  varInd <- sets[["wide panel"]][["id"]]
  varTime <- sets[["wide panel"]][["time"]]
  index <- c(varInd, varTime)
  varY <- sets[["wide panel"]][["Yname"]]
  varD <- sets[["wide panel"]][["Dname"]]
  varX <- sets[["wide panel"]][["Xname"]]
  
  ## get the tuning parameters
  c <- as.numeric(sets[["tuning parameters"]][["carryover"]])
  a <- as.numeric(sets[["tuning parameters"]][["pre_treatment"]])
  b <- as.numeric(sets[["tuning parameters"]][["post_treatment"]])
  
  ## get the matrix of match
  matching_set <- sets[["matrix of match"]][["M_match"]]
  
  ## get the dimensions of the wide panel
  TT <- dim(Dwide)[1]
  N <- dim(Dwide)[2]
  
  ## get the estimated coefficients
  if (estimand == "Dynamic"){
    coefs <- getCoefs(Y = Ywide, 
                    D = Dwide, 
                    X = Xwide, 
                    c = c, 
                    a = a, 
                    b = b, 
                    matching_set = matching_set, 
                    estimand = "Dynamic",
                    method = "Simple DID")
  } else if (estimand == "ATT"){
    coefs <- getCoefs(Y = Ywide, 
                    D = Dwide, 
                    X = Xwide, 
                    c = c, 
                    a = a, 
                    b = b, 
                    matching_set = matching_set, 
                    estimand = "ATT",
                    method = "Simple DID")
  }
  
  if (vce == "jackknife"){
    if (estimand == "ATT"){ # We use jackknife to get the confidence interval of ATT
      jackout <- matrix(NA, nrow=1, ncol=N)
      for (i in 1:N) {  
        # whether we drop a treated unit  
        rows_to_delete <- matching_set[, 1] == i  
        # delete the episode w.r.t. this unit if exist  
        matching_set_tmp <- matching_set[!rows_to_delete, , drop = FALSE] 
        # change the control list w.r.t. unit i to 0 for all episodes
        matching_set_tmp[, i+2] <- 0
        # estimation for the i-th jackknife
        jackout[, i] <- getCoefs(Y = Ywide, 
                        D = Dwide, 
                        X = Xwide, 
                        c = c, 
                        a = a, 
                        b = b, 
                        matching_set = matching_set_tmp, 
                        estimand = "ATT",
                        method = "Simple DID")
        if (i%%50 == 0) cat(i) else cat(".")
      }
      # use the normal approximation
      coefs_bar <- rowMeans(jackout, na.rm = TRUE)
      var <- (jackout-coefs_bar) %*% (t(jackout-coefs_bar))*(N-1)/N
      se <- sqrt(var)
      CI <- c(coefs-qnorm(1-alpha/2, mean = 0, sd = 1)*se, coefs+qnorm(1-alpha/2, mean = 0, sd = 1)*se)
      est <- as.data.frame(cbind(coefs, CI))
      colnames(est) = c("Coefs", "CI.lower", "CI.upper")
      return(est)
    } else if (estimand == "Dynamic"){ # We use jackknife to get the confidence interval of ATT
      jackout <- matrix(NA, nrow=a+1+b, ncol=N)
      for (i in 1:N) {  
        # whether we drop a treated unit  
        rows_to_delete <- matching_set[, 1] == i  
        # delete the episode w.r.t. this unit if exist  
        matching_set_tmp <- matching_set[!rows_to_delete, , drop = FALSE] 
        # change the control list w.r.t. unit i to 0 for all episodes
        matching_set_tmp[, i+2] <- 0
        # estimation for the i-th jackknife
        jackout[, i] <- t(getCoefs(Y = Ywide, 
                                 D = Dwide, 
                                 X = Xwide, 
                                 c = c, 
                                 a = a, 
                                 b = b, 
                                 matching_set = matching_set_tmp, 
                                 estimand = "Dynamic",
                                 method = "Simple DID"))
        if (i%%50 == 0) cat(i) else cat(".")
      }
      # use the normal approximation
      coefs_bar <- matrix(rep(matrix(rowMeans(jackout, na.rm = TRUE)), N), nrow = nrow(jackout))
      var <- t(rowSums((jackout-coefs_bar)*(jackout-coefs_bar))*(N-1)/N)
      se <- sqrt(var)
      CI <- t(rbind(coefs-qnorm(1-alpha/2, mean = 0, sd = 1)*se, coefs+qnorm(1-alpha/2, mean = 0, sd = 1)*se))
      periods <- c(-a:-1,0,1:b)
      est <- as.data.frame(cbind(periods, coefs, CI))
      colnames(est) = c("Periods","Coefs", "CI.lower", "CI.upper")
      return(est)
    }
  } else if (vce == "bootstrap"){
    if (estimand == "ATT"){ # We use bootstrap to get the confidence interval of ATT
      bootout <- matrix(NA, nrow=1, ncol=nsim)
      for (i in 1:nsim){
        set.seed(i) # locally set seed, so that the outputs can be replicated
        smp <- sample(1:N, N, replace=TRUE)
        Yboot <- Ywide[, smp]
        Dboot <- Dwide[, smp]
        Xboot <- list()  
        for (p in 1:length(Xwide)) {  
          Xboot[[paste0("Xwide", p)]] <- Xwide[[p]][, smp] 
        }
        data_long <- wide2long(Y = Yboot,
                               D = Dboot,
                               X = Xboot,
                               varInd = varInd,
                               varTime = varTime,
                               varY = varY,
                               varD = varD,
                               varX = varX)
        epiboot <- matching(data = data_long, # data in long form
                         Y = varY, # outcome
                         D = varD, # treatment
                         X = varX, # covariates
                         index = index, # unit and time
                         c = c, # number of carryover effect period 
                         a = a, # number of pre-treatment period, lag
                         b = b, # number of post-treatment period, lead
                         type = "episode")
        matching_set_boot <- epiboot[["matrix of match"]][["M_match"]]
        bootout[, i] <- getCoefs(Y = Yboot, 
                                 D = Dboot, 
                                 X = Xboot, 
                                 c = c, 
                                 a = a, 
                                 b = b, 
                                 matching_set = matching_set_boot, 
                                 estimand = "ATT",
                                 method = "Simple DID")
        if (i%%50 == 0) cat(i) else cat(".")
      }
      CI <- t(apply(bootout, 1, quantile,c(alpha/2,1-alpha/2)))
      est <- as.data.frame(cbind(coefs, CI))
      colnames(est) = c("Coefs", "CI.lower", "CI.upper")
      return(est)
    } else if (estimand == "Dynamic"){ # We use bootstrap to get the confidence intervals of dynamic effects
      bootout <- matrix(NA, nrow=a+1+b, ncol=nsim)
      for (i in 1:nsim){
        set.seed(i) # locally set seed, so that the outputs can be replicated
        smp <- sample(1:N, N, replace=TRUE)
        Yboot <- Ywide[, smp]
        Dboot <- Dwide[, smp]
        Xboot <- list()  
        for (p in 1:length(Xwide)) {  
          Xboot[[paste0("Xwide", p)]] <- Xwide[[p]][, smp] 
        }
        data_long <- wide2long(Y = Yboot,
                               D = Dboot,
                               X = Xboot,
                               varInd = varInd,
                               varTime = varTime,
                               varY = varY,
                               varD = varD,
                               varX = varX)
        epiboot <- matching(data = data_long, # data in long form
                         Y = varY, # outcome
                         D = varD, # treatment
                         X = varX, # covariates
                         index = index, # unit and time
                         c = c, # number of carryover effect period 
                         a = a, # number of pre-treatment period, lag
                         b = b, # number of post-treatment period, lead
                         type = "episode")
        matching_set_boot <- epiboot[["matrix of match"]][["M_match"]]
        bootout[, i] <- t(getCoefs(Y = Yboot, 
                                 D = Dboot, 
                                 X = Xboot, 
                                 c = c, 
                                 a = a, 
                                 b = b, 
                                 matching_set = matching_set_boot, 
                                 estimand = "Dynamic",
                                 method = "Simple DID"))
        if (i%%50 == 0) cat(i) else cat(".")
      }
      CI <- t(apply(bootout, 1, quantile,c(alpha/2,1-alpha/2)))
      periods <- c(-a:-1,0,1:b)
      est <- as.data.frame(cbind(periods, coefs, CI))
      colnames(est) = c("Periods","Coefs", "CI.lower", "CI.upper")
      return(est)
    }
  } else{
    stop("The package only supports jackknife or bootstrap now.")
  }
}

getCoefs <- function(Y, D, X, c, a, b, matching_set, estimand, method){
  
  if (method == "Simple DID"){ # We use simple mean of the outcome
    if (estimand == "ATT"){ # We estimate the average treatment effect
      est <- matrix(NA, nrow=dim(matching_set)[1], ncol=1)
      for (i in 1:dim(matching_set)[1]){
        # get the indicator for the treated unit, treated time and control unit
        INDtreat <- as.vector(matching_set[i,1])
        INDtime <- as.vector(matching_set[i,2])
        INDcontrol <- as.vector(matching_set[i, -1:-2])
        # get the matrix respectively
        Ytreat <- as.matrix(Y[(INDtime-c-a):(INDtime+b), INDtreat], nrow=c+a+1+b, ncol=1) # initial Ytreat
        Ycontrol <- as.matrix(Y[(INDtime-c-a):(INDtime+b), (INDcontrol==1)], nrow=c+a+1+b, ncol=sum(matching_set[i, -1:-2])) # initial Ycontrol
        # simple DID: Difference in mean
        Ytreatpost <- mean(Ytreat[(c+a+1):(c+a+1+b),])
        Ytreatpre <- mean(Ytreat[(c+1):(c+a),])
        Ycontrolpost <- mean(Ycontrol[(c+a+1):(c+a+1+b),])
        Ycontrolpre <- mean(Ycontrol[(c+1):(c+a),])
        est[i,] <- (Ytreatpost-Ytreatpre)-(Ycontrolpost-Ycontrolpre)
      }
      ATT <- mean(est, na.rm = TRUE)
      return(ATT)
    } else if (estimand == "Dynamic"){ # We estimate the dynamic treatment effect
      est_dynamic <- matrix(NA, nrow=dim(matching_set)[1], ncol=a+1+b)
      for (i in 1:dim(matching_set)[1]){
        # get the indicator for the treated unit, treated time and control unit
        INDtreat <- as.vector(matching_set[i,1])
        INDtime <- as.vector(matching_set[i,2])
        INDcontrol <- as.vector(matching_set[i,-1:-2])
        # get the matrix respectively
        Ytreat <- as.matrix(Y[(INDtime-c-a):(INDtime+b),INDtreat],nrow=c+a+1+b,ncol=1) # initial Ytreat
        Ycontrol <- as.matrix(Y[(INDtime-c-a):(INDtime+b),(INDcontrol==1)],nrow=c+a+1+b,ncol=sum(matching_set[i,-1:-2])) # initial Ycontrol
        # dynamic DID: Difference in mean for each period
        Ytreatbench <- matrix(mean(Ytreat[(c+1):(c+a),]),nrow=a+1+b,ncol=1) # using the whole pre-treatment period as benchmark
        Ycontrolbench <- matrix(mean(Ycontrol[(c+1):(c+a),]),nrow=a+1+b,ncol=1) # using the whole pre-treatment period as benchmark
        Ytreatdyn <- matrix(Ytreat[(c+1):(c+a+1+b),],nrow=a+1+b,ncol=1)
        Ycontroldyn <- as.matrix(rowMeans(Ycontrol[(c+1):(c+a+1+b),]),nrow=a+1+b,ncol=1)
        est_dynamic[i,] <- t((Ytreatdyn-Ycontroldyn)-(Ytreatbench-Ycontrolbench))
      }
      Dynamic <- colMeans(est_dynamic, na.rm = TRUE)
      return(Dynamic)
    }
  } else{
    stop("Other method will be added in the later version.")
  }
}

wide2long <- function(Y, D, X, varInd, varTime, varY, varD, varX){
  
  TT <- dim(D)[1] # length of time
  N <- dim(D)[2] # length of unit
  
  if (is.null(X) & is.null(varX)){ # The panel does not include covariates
    Ylong <- matrix(Y, nrow = TT*N, ncol = 1) # long panel for Y
    Dlong <- matrix(D, nrow = TT*N, ncol = 1) # long panel for D
    
    time_long <- matrix(as.matrix(replicate(N,c(1:TT))), nrow = TT*N, ncol = 1)
    unit_long <- matrix(as.matrix(t(replicate(TT,c(1:N)))), nrow = TT*N, ncol = 1)
    
    data_long <- as.data.frame(cbind(unit_long, time_long, Ylong, Dlong))
    colnames(data_long) = c(varInd, varTime, varY, varD)
    # the first column is ind i, the second column is time t, 
    # the third column is outcome Y, the fourth column is treatment D
    return(data_long)
  } else{ # The panel includes covariates
    Ylong <- matrix(Y, nrow = TT*N, ncol = 1) # long panel for Y
    Dlong <- matrix(D, nrow = TT*N, ncol = 1) # long panel for D
    Xlong <- matrix(0, nrow = N*TT, ncol = length(varX))
    for (p in 1:length(varX)) {  
      Xlong[,p] <- matrix(X[[paste0("Xwide", p)]], nrow = TT*N, ncol = 1)  
    } # long panel for X
    
    time_long <- matrix(as.matrix(replicate(N,c(1:TT))), nrow = TT*N, ncol = 1)
    unit_long <- matrix(as.matrix(t(replicate(TT,c(1:N)))), nrow = TT*N, ncol = 1)
    
    data_long <- as.data.frame(cbind(unit_long, time_long, Ylong, Dlong, Xlong))
    colnames(data_long) = c(varInd, varTime, varY, varD, varX)
    # the first column is ind i, the second column is time t, 
    # the third column is outcome Y, the fourth column is treatment D, the rest are control variables X
    return(data_long)
  }
}

