#' @title matching.CI  
#'  
#' @description \code{matching.CI} give the estimates of the match episode, using different 
#' estimator or inference.  
#'  
#' @param sets episode generated by match.R
#' @param alpha significance level
#' @param estimand "ATT" or "Dynamic"
#' @param method "Simple DID" now, can be added in later version
#' @param vce "jackknife" or "bootstrap"
#' @param nsim numbers of bootstrap, also used for limit the number of jackknife
#' @param parallel whether do parallel computing
#' @param cores cores used in the parallel computing
#' @param demean used in mbal/kbal
#' @param imbal.tol used in mbal/kbal, if FALSE, will only keep the episodes with bias.ratio < 1e-5
#' @param term.alpha named vector of ridge penalties, only takes 0 or 1
#' @param cv whether to use cross validation
#'  
#' @return \code{matching.CI} return a dataframe containing the periods, estimates, and the CI
#' @author Hongyi Jiang <hyjiang2017@nsd.pku.edu.cn>
#'  
#' @export
matching.CI <- function(sets, 
                     alpha = 0.05, 
                     estimand = "Dynamic", 
                     method = "Simple DID", 
                     vce = "jackknife", 
                     nsim = 200,
                     parallel = TRUE, ## parallel computing
                     cores = 4,
                     demean = TRUE,
                     imbal.tol = FALSE,
                     term.alpha = NULL,
                     cv = NULL
                     ){
  # get the confidence interval of treatment effect
  
  # sets: a list which contains the wide raw balanced panel, the matrix of match,
  # the true id and time, the uning parameters c, a, b, and each episode/cohort
  # alpha: significance level, 0.05 by default
  # estimand: dynamic by default, can be ATT or dynamic
  # method: jackknife by default, can be bootstrap or jackknife
  # nsim: number of bootstrap, will not be used when method == "jackknife"
  
  ## get the wide panel data
  Ywide <- sets[["wide panel"]][["Ywide"]]
  Dwide <- sets[["wide panel"]][["Dwide"]]
  Xwide <- sets[["wide panel"]][["Xwide"]]
  
  ## get the variable names
  varInd <- sets[["wide panel"]][["id"]]
  varTime <- sets[["wide panel"]][["time"]]
  index <- c(varInd, varTime)
  varY <- sets[["wide panel"]][["Yname"]]
  varD <- sets[["wide panel"]][["Dname"]]
  varX <- sets[["wide panel"]][["Xname"]]
  
  ## get the tuning parameters
  c <- as.numeric(sets[["tuning parameters"]][["carryover"]])
  a <- as.numeric(sets[["tuning parameters"]][["pre_treatment"]])
  b <- as.numeric(sets[["tuning parameters"]][["post_treatment"]])
  
  ## get the matrix of match
  matching_set <- sets[["matrix of match"]][["M_match"]]
  
  ## get the dimensions of the wide panel
  TT <- dim(Dwide)[1]
  N <- dim(Dwide)[2]
  
  ## get the estimated coefficients
  coefs <- getCoefs(Y = Ywide, 
                    D = Dwide, 
                    X = Xwide,
                    varY = varY,  
                    varD = varD, 
                    varX = varX,
                    c = c, 
                    a = a, 
                    b = b, 
                    matching_set = matching_set, 
                    estimand = estimand,
                    method = method,
                    demean = demean,
                    imbal.tol = imbal.tol,
                    term.alpha = term.alpha,
                    cv = cv
                    )
  
  ## uncertainty estimates
  if (vce == "jackknife"){
    if (nsim > N) {
      njacks <- N
    } else {
      njacks <- nsim
    }
    drop.id <- sample(1:N, njacks, replace = FALSE)
    if (estimand == "ATT"){ # We use jackknife to get the confidence interval of ATT
      cat("\nJackknife for ATT... \n")
      jackout <- matrix(NA, nrow=1, ncol=njacks)
      if (parallel == TRUE){
        ## prepare
        if (is.null(cores) == TRUE) {
          cores <- detectCores() - 2
        }
        para.clusters <- makeCluster(cores)
        registerDoParallel(para.clusters)
        ## start    
        cat("Parallel computing...")
        jackout <- foreach(i = 1:njacks, .combine = cbind,   
                           .packages = "paneltools") %dopar% {  
        rows_to_delete <- matching_set[, 1] == drop.id[i]  
        matching_set_tmp <- matching_set[!rows_to_delete, , drop = FALSE]  
        matching_set_tmp[, drop.id[i]+2] <- 0  
        getCoefs(Y = Ywide, 
                 D = Dwide, 
                 X = Xwide,
                 varY = varY,  
                 varD = varD, 
                 varX = varX,
                 c = c, 
                 a = a,  
                 b = b, 
                 matching_set = matching_set_tmp, 
                 estimand = "ATT", 
                 method = method,
                 demean = demean,
                 imbal.tol = imbal.tol,
                 term.alpha = term.alpha,
                 cv = cv
        )  
                           }  
        stopCluster(para.clusters)
      } else { # single core
        for (i in 1:njacks) {  
          # whether we drop a treated unit  
          rows_to_delete <- matching_set[, 1] == drop.id[i]  
          # delete the episode w.r.t. this unit if exist  
          matching_set_tmp <- matching_set[!rows_to_delete, , drop = FALSE] 
          # change the control list w.r.t. unit i to 0 for all episodes
          matching_set_tmp[, drop.id[i]+2] <- 0
          # estimation for the i-th jackknife
          jackout[, i] <- getCoefs(Y = Ywide, 
                                   D = Dwide, 
                                   X = Xwide,
                                   varY = varY,  
                                   varD = varD, 
                                   varX = varX,
                                   c = c, 
                                   a = a, 
                                   b = b, 
                                   matching_set = matching_set_tmp, 
                                   estimand = "ATT",
                                   method = method,
                                   demean = demean,
                                   imbal.tol = imbal.tol,
                                   term.alpha = term.alpha,
                                   cv = cv
          )
          if (i%%50 == 0) cat(i) else cat(".")
        }
      }
      # use the normal approximation
      coefs_bar <- rowMeans(jackout, na.rm = TRUE)
      var <- (jackout-coefs_bar) %*% (t(jackout-coefs_bar))*(njacks-1)/njacks
      se <- sqrt(var)
      CI <- c(coefs-qnorm(1-alpha/2, mean = 0, sd = 1)*se, coefs+qnorm(1-alpha/2, mean = 0, sd = 1)*se)
      est <- as.data.frame(cbind(coefs, CI))
      colnames(est) = c("Coefs", "CI.lower", "CI.upper")
      return(est)
    } else if (estimand == "Dynamic"){ # We use jackknife to get the confidence interval of ATT
      cat("\nJackknife for Dynamic... \n")
      jackout <- matrix(NA, nrow=a+1+b, ncol=njacks)
      if (parallel == TRUE){
        ## prepare
        if (is.null(cores) == TRUE) {
          cores <- detectCores() - 2
        }
        para.clusters <- makeCluster(cores)
        registerDoParallel(para.clusters)
        ## start    
        cat("Parallel computing...")
        jackout <- foreach(i = 1:njacks, .combine = cbind,   
                           .packages = "paneltools") %dopar% {  
        rows_to_delete <- matching_set[, 1] == drop.id[i]  
        matching_set_tmp <- matching_set[!rows_to_delete, , drop = FALSE]  
        matching_set_tmp[, drop.id[i]+2] <- 0  
        getCoefs(Y = Ywide, 
                 D = Dwide, 
                 X = Xwide,
                 varY = varY,  
                 varD = varD, 
                 varX = varX,
                 c = c, 
                 a = a, 
                 b = b,  
                 matching_set = matching_set_tmp, 
                 estimand = "Dynamic", 
                 method = method,
                 demean = demean,
                 imbal.tol = imbal.tol,
                 term.alpha = term.alpha,
                 cv = cv
        )  
                           }  
        stopCluster(para.clusters)
      } else { # single core
        for (i in 1:njacks) {  
          # whether we drop a treated unit  
          rows_to_delete <- matching_set[, 1] == drop.id[i]  
          # delete the episode w.r.t. this unit if exist  
          matching_set_tmp <- matching_set[!rows_to_delete, , drop = FALSE] 
          # change the control list w.r.t. unit i to 0 for all episodes
          matching_set_tmp[, drop.id[i]+2] <- 0
          # estimation for the i-th jackknife
          jackout[, i] <- getCoefs(Y = Ywide, 
                                   D = Dwide, 
                                   X = Xwide, 
                                   varY = varY,  
                                   varD = varD, 
                                   varX = varX,
                                   c = c, 
                                   a = a, 
                                   b = b, 
                                   matching_set = matching_set_tmp, 
                                   estimand = "Dynamic",
                                   method = method,
                                   demean = demean,
                                   imbal.tol = imbal.tol,
                                   term.alpha = term.alpha,
                                   cv = cv
          )
          if (i%%50 == 0) cat(i) else cat(".")
        }
      }
      # use the normal approximation
      coefs_bar <- matrix(rep(matrix(rowMeans(jackout, na.rm = TRUE)), njacks), nrow = nrow(jackout))
      var <- t(rowSums((jackout-coefs_bar)*(jackout-coefs_bar))*(njacks-1)/njacks)
      se <- sqrt(var)
      CI <- t(rbind(coefs-qnorm(1-alpha/2, mean = 0, sd = 1)*se, coefs+qnorm(1-alpha/2, mean = 0, sd = 1)*se))
      periods <- c(-a:-1,0,1:b)
      est <- as.data.frame(cbind(periods, coefs, CI))
      colnames(est) = c("Periods","Coefs", "CI.lower", "CI.upper")
      return(est)
    }
  } else if (vce == "bootstrap"){
    if (estimand == "ATT"){ # We use bootstrap to get the confidence interval of ATT
      cat("\nBootstrapping for ATT... \n")
      bootout <- matrix(NA, nrow=1, ncol=nsim)
      if (parallel == TRUE){
        ## prepare
        if (is.null(cores) == TRUE) {
          cores <- detectCores() - 2
        }
        para.clusters <- makeCluster(cores)
        registerDoParallel(para.clusters)
        ## start    
        cat("Parallel computing...")
        bootout <- foreach(i = 1:nsim, .combine = cbind,  
                           .packages = c("paneltools", "stats")) %dopar% {  
        smp <- sample(1:N, N, replace=TRUE)  
        Yboot <- Ywide[, smp]  
        Dboot <- Dwide[, smp]
        if (is.null(Xwide)){
          Xboot <- NULL
        } else{
          Xboot <- lapply(Xwide, function(x) x[, smp, drop = FALSE])
        }
        data_long <- wide2long(Y = Yboot,
                               D = Dboot,  
                               X = Xboot, 
                               varInd = varInd, 
                               varTime = varTime, 
                               varY = varY,  
                               varD = varD, 
                               varX = varX)  
        epiboot <- matching(data = data_long,
                            Y = varY, 
                            D = varD, 
                            X = varX,  
                            index = index,  
                            c = c, 
                            a = a, 
                            b = b, 
                            type = "episode")  
        matching_set_boot <- epiboot[["matrix of match"]][["M_match"]]  
        getCoefs(Y = Yboot, 
                 D = Dboot,  
                 X = Xboot, 
                 varY = varY,  
                 varD = varD, 
                 varX = varX,
                 c = c,  
                 a = a, 
                 b = b,
                 matching_set = matching_set_boot, 
                 estimand = "ATT", 
                 method = method,
                 demean = demean,
                 imbal.tol = imbal.tol,
                 term.alpha = term.alpha,
                 cv = cv
        )  
                           }    
        stopCluster(para.clusters)
      } else { # single core
        for (i in 1:nsim){
          # set.seed(i) # locally set seed, so that the outputs can be replicated
          smp <- sample(1:N, N, replace=TRUE)
          Yboot <- Ywide[, smp]
          Dboot <- Dwide[, smp]
          if (is.null(Xwide)){
            Xboot <- NULL
          } else{
            Xboot <- lapply(Xwide, function(x) x[, smp, drop = FALSE])
            # Xboot <- list()  
            # for (p in 1:length(Xwide)) {  
            # Xboot[[paste0("Xwide", p)]] <- Xwide[[p]][, smp] 
            # }
          }
          data_long <- wide2long(Y = Yboot,
                                 D = Dboot,
                                 X = Xboot,
                                 varInd = varInd,
                                 varTime = varTime,
                                 varY = varY,
                                 varD = varD,
                                 varX = varX)
          epiboot <- matching(data = data_long, # data in long form
                              Y = varY, # outcome
                              D = varD, # treatment
                              X = varX, # covariates
                              index = index, # unit and time
                              c = c, # number of carryover effect period 
                              a = a, # number of pre-treatment period, lag
                              b = b, # number of post-treatment period, lead
                              type = "episode")
          matching_set_boot <- epiboot[["matrix of match"]][["M_match"]]
          bootout[, i] <- getCoefs(Y = Yboot, 
                                   D = Dboot, 
                                   X = Xboot,
                                   varY = varY,  
                                   varD = varD, 
                                   varX = varX,
                                   c = c, 
                                   a = a, 
                                   b = b, 
                                   matching_set = matching_set_boot, 
                                   estimand = "ATT",
                                   method = method,
                                   demean = demean,
                                   imbal.tol = imbal.tol,
                                   term.alpha = term.alpha,
                                   cv = cv
          )
          if (i%%50 == 0) cat(i) else cat(".")
        }
      }
      # CI <- t(apply(bootout, 1, quantile,c(alpha/2,1-alpha/2)))
      CI <- t(apply(bootout, 1, quantile, probs = c(alpha/2, 1 - alpha/2), na.rm = TRUE))
      est <- as.data.frame(cbind(coefs, CI))
      colnames(est) = c("Coefs", "CI.lower", "CI.upper")
      return(est)
    } else if (estimand == "Dynamic"){ # We use bootstrap to get the confidence intervals of dynamic effects
      cat("\nBootstrapping for Dynamic... \n")
      bootout <- matrix(NA, nrow=a+1+b, ncol=nsim)
      if (parallel == TRUE){
        ## prepare
        if (is.null(cores) == TRUE) {
          cores <- detectCores() - 2
        }
        para.clusters <- makeCluster(cores)
        registerDoParallel(para.clusters)
        ## start    
        cat("Parallel computing...")
        bootout <- foreach(i = 1:nsim, .combine = cbind,  
                           .packages = c("paneltools", "stats")) %dopar% {  
        smp <- sample(1:N, N, replace=TRUE)  
        Yboot <- Ywide[, smp]  
        Dboot <- Dwide[, smp]
        if (is.null(Xwide)){
          Xboot <- NULL
        } else{
          Xboot <- lapply(Xwide, function(x) x[, smp, drop = FALSE])
        }
        data_long <- wide2long(Y = Yboot,
                               D = Dboot, 
                               X = Xboot, 
                               varInd = varInd, 
                               varTime = varTime, 
                               varY = varY,
                               varD = varD, 
                               varX = varX)  
        epiboot <- matching(data = data_long,
                            Y = varY,
                            D = varD,
                            X = varX,
                            index = index,
                            c = c,
                            a = a,
                            b = b,
                            type = "episode")  
        matching_set_boot <- epiboot[["matrix of match"]][["M_match"]]  
        getCoefs(Y = Yboot, 
                 D = Dboot, 
                 X = Xboot,
                 varY = varY,  
                 varD = varD, 
                 varX = varX,
                 c = c, 
                 a = a, 
                 b = b,
                 matching_set = matching_set_boot, 
                 estimand = "Dynamic",
                 method = method,
                 demean = demean,
                 imbal.tol = imbal.tol,
                 term.alpha = term.alpha,
                 cv = cv
        )  
                           }    
        stopCluster(para.clusters)
      } else { # single core
        for (i in 1:nsim){
          # set.seed(i) # locally set seed, so that the outputs can be replicated
          smp <- sample(1:N, N, replace=TRUE)
          Yboot <- Ywide[, smp]
          Dboot <- Dwide[, smp]
          if (is.null(Xwide)){
            Xboot <- NULL
          } else{
            Xboot <- lapply(Xwide, function(x) x[, smp, drop = FALSE])
            # Xboot <- list()  
            # for (p in 1:length(Xwide)) {  
            # Xboot[[paste0("Xwide", p)]] <- Xwide[[p]][, smp] 
            # }
          }
          data_long <- wide2long(Y = Yboot,
                                 D = Dboot,
                                 X = Xboot,
                                 varInd = varInd,
                                 varTime = varTime,
                                 varY = varY,
                                 varD = varD,
                                 varX = varX)
          epiboot <- matching(data = data_long, # data in long form
                              Y = varY, # outcome
                              D = varD, # treatment
                              X = varX, # covariates
                              index = index, # unit and time
                              c = c, # number of carryover effect period 
                              a = a, # number of pre-treatment period, lag
                              b = b, # number of post-treatment period, lead
                              type = "episode")
          matching_set_boot <- epiboot[["matrix of match"]][["M_match"]]
          bootout[, i] <- getCoefs(Y = Yboot, 
                                   D = Dboot, 
                                   X = Xboot,
                                   varY = varY,  
                                   varD = varD, 
                                   varX = varX,
                                   c = c, 
                                   a = a, 
                                   b = b, 
                                   matching_set = matching_set_boot, 
                                   estimand = "Dynamic",
                                   method = method,
                                   demean = demean,
                                   imbal.tol = imbal.tol,
                                   term.alpha = term.alpha,
                                   cv = cv
          )
          if (i%%50 == 0) cat(i) else cat(".")
        }
      }
      # CI <- t(apply(bootout, 1, quantile,c(alpha/2,1-alpha/2)))
      CI <- t(apply(bootout, 1, quantile, probs = c(alpha/2, 1 - alpha/2), na.rm = TRUE))
      periods <- c(-a:-1,0,1:b)
      est <- as.data.frame(cbind(periods, coefs, CI))
      colnames(est) = c("Periods","Coefs", "CI.lower", "CI.upper")
      return(est)
    }
  } else{
    stop("The package only supports jackknife or bootstrap now.")
  }
}

getCoefs <- function(Y, 
                     D, 
                     X, 
                     varY, 
                     varD, 
                     varX, 
                     c, 
                     a, 
                     b, 
                     matching_set, 
                     estimand, 
                     method, 
                     demean = TRUE, 
                     imbal.tol = FALSE,
                     term.alpha = NULL,
                     cv = NULL
                     ){
  
  est <- matrix(NA, nrow=dim(matching_set)[1], ncol=1)
  est_dynamic <- matrix(NA, nrow=dim(matching_set)[1], ncol=a+1+b)
  
  for (i in 1:dim(matching_set)[1]){
    # get the indicator for the treated unit, treated time and control unit
    INDtreat <- as.vector(matching_set[i,1])
    INDtime <- as.vector(matching_set[i,2])
    INDcontrol <- as.vector(matching_set[i, -1:-2])
    
    # other columns
    Ntmp <- 1 + sum(matching_set[i, -1:-2])
    unitstmp <- matrix(NA, nrow = Ntmp, ncol = 1) 
    unitstmp[1,1] <- INDtreat
    unitstmp[-1,1] <- as.matrix(1:length(INDcontrol),nrow=1,ncol=length(INDcontrol))[(INDcontrol==1)]
    treattmp <- matrix(0, nrow = Ntmp, ncol = 1)
    treattmp[1,1] <- 1
    T0tmp <- matrix(a, nrow = Ntmp, ncol = 1)
    
    # preparation
    if (is.null(X) & is.null(varX)){
      # get Y
      Ytreat <- as.matrix(Y[(INDtime-a):(INDtime+b), INDtreat], nrow=a+1+b, ncol=1) # initial Ytreat
      Ycontrol <- as.matrix(Y[(INDtime-a):(INDtime+b), (INDcontrol==1)], nrow=a+1+b, ncol=sum(matching_set[i, -1:-2])) # initial Ycontrol
      outcome <- t(cbind(Ytreat,Ycontrol))
      Ttot <- as.matrix(1:(a+1+b),nrow=a+1+b ,ncol=1)
      Y.var <- paste0(varY, Ttot)
      colnames(outcome) <- Y.var
      data.wide <- cbind.data.frame(id = 1:Ntmp, unit = unitstmp, treat = treattmp, T0 = T0tmp, outcome)
    } else{
      # get Y
      Ytreat <- as.matrix(Y[(INDtime-a):(INDtime+b), INDtreat], nrow=a+1+b, ncol=1) # initial Ytreat
      Ycontrol <- as.matrix(Y[(INDtime-a):(INDtime+b), (INDcontrol==1)], nrow=a+1+b, ncol=sum(matching_set[i, -1:-2])) # initial Ycontrol
      outcome <- t(cbind(Ytreat,Ycontrol))
      Ttot <- as.matrix(1:(a+1+b),nrow=a+1+b ,ncol=1)
      Y.var <- paste0(varY, Ttot)
      colnames(outcome) <- Y.var
      # get X
      Xtreat <- matrix(NA, nrow = 1, ncol = length(varX))
      Xcontrol <- matrix(NA, nrow = sum(matching_set[i, -1:-2]), ncol = length(varX))
      for (p in 1:length(varX)) {  
        Xtreat[, p] <- t(mean(X[[paste0("Xwide", p)]][(INDtime-a):(INDtime-1), INDtreat]))
        Xcontrol[, p] <- t(colMeans(X[[paste0("Xwide", p)]][(INDtime-a):(INDtime-1), (INDcontrol==1)])) 
      }
      Xvar <- rbind(Xtreat,Xcontrol)
      colnames(Xvar) <- varX
      data.wide <- cbind.data.frame(id = 1:Ntmp, unit = unitstmp, treat = treattmp, T0 = T0tmp, outcome, Xvar)
    }
    id.tr <- which(data.wide$treat == 1)
    id.co <- which(data.wide$treat == 0)
    T0 <- unique(data.wide$T0[id.tr])
    
    if (method == "Simple DID"){
      # simple DID: Difference in mean
      Ytreatpost <- mean(Ytreat[(a+1):(a+1+b),])
      Ytreatpre <- mean(Ytreat[1:a,])
      Ycontrolpost <- mean(Ycontrol[(a+1):(a+1+b),])
      Ycontrolpre <- mean(Ycontrol[1:a,])
      est[i,] <- (Ytreatpost-Ytreatpre)-(Ycontrolpost-Ycontrolpre)
      # dynamic DID: Difference in mean for each period
      Ytreatbench <- matrix(mean(Ytreat[1:a,]),nrow=a+1+b,ncol=1) # using the whole pre-treatment period as benchmark
      Ycontrolbench <- matrix(mean(Ycontrol[1:a,]),nrow=a+1+b,ncol=1) # using the whole pre-treatment period as benchmark
      Ytreatdyn <- matrix(Ytreat[1:(a+1+b),],nrow=a+1+b,ncol=1)
      Ycontroldyn <- as.matrix(rowMeans(Ycontrol[1:(a+1+b),]),nrow=a+1+b,ncol=1)
      est_dynamic[i,] <- t((Ytreatdyn-Ycontroldyn)-(Ytreatbench-Ycontrolbench))
    } else if (method == "mbal"){ # "mbal"
      out <- tjbal.core(data = data.wide, Y = varY, X = varX, Ttot = Ttot, T0 = T0, id.tr = id.tr, id.co = id.co,
                        demean = demean, estimator = "mean", info = FALSE, balance.table = FALSE)
      if (imbal.tol == TRUE){
        est[i,] <- out$att.avg
        for (p in 1:(a+1+b)) {  
        est_dynamic[i, p] <- out[["att"]][[p]]
        }
      } else{
        if (out$bias.ratio < 1e-5){
          est[i,] <- out$att.avg
          for (p in 1:(a+1+b)) {  
            est_dynamic[i, p] <- out[["att"]][[p]]
          }
        }
      }
    } else if (method == "kbal"){ # "kbal"
      out <- tjbal.core(data = data.wide, Y = varY, X = varX, Ttot = Ttot, T0 = T0, id.tr = id.tr, id.co = id.co,
                        demean = demean, estimator = "kernel", info = FALSE, balance.table = FALSE)
      if (imbal.tol == TRUE){
        est[i,] <- out$att.avg
        for (p in 1:(a+1+b)) {  
          est_dynamic[i, p] <- out[["att"]][[p]]
        }
      } else{
        if (out$bias.ratio < 1e-5){
          est[i,] <- out$att.avg
          for (p in 1:(a+1+b)) {  
            est_dynamic[i, p] <- out[["att"]][[p]]
          }
        }
      }
    } else if (method == "hbal"){ # "hbal"
      Tpre <- as.matrix(1:a, nrow=a, ncol=1)
      xvars <- c(paste0(varY, Tpre), varX) # covariates
      hbal.out <- hbal(Treat = 'treat', X = xvars, data = data.wide, term.alpha = term.alpha, cv = cv)
      if (hbal.out$converged == 1){
        w <- -hbal.out$weights
        w[1] <- 1
        est_dynamic[i,] <- w %*% outcome
        est[i,] <- mean((w %*% outcome)[,(a+1):(a+1+b)])
      }
    }
    
  }
  
  # output
  ATT <- mean(est, na.rm = TRUE)
  Dynamic <- colMeans(est_dynamic, na.rm = TRUE)
  if (estimand == "ATT"){
    return(ATT)
  } else if (estimand == "Dynamic"){
    return(Dynamic)
  }
}

wide2long <- function(Y,
                      D,
                      X, 
                      varInd,
                      varTime,
                      varY, 
                      varD, 
                      varX){
  
  TT <- dim(D)[1] # length of time
  N <- dim(D)[2] # length of unit
  
  if (is.null(X) & is.null(varX)){ # The panel does not include covariates
    Ylong <- matrix(Y, nrow = TT*N, ncol = 1) # long panel for Y
    Dlong <- matrix(D, nrow = TT*N, ncol = 1) # long panel for D
    
    time_long <- matrix(as.matrix(replicate(N,c(1:TT))), nrow = TT*N, ncol = 1)
    unit_long <- matrix(as.matrix(t(replicate(TT,c(1:N)))), nrow = TT*N, ncol = 1)
    
    data_long <- as.data.frame(cbind(unit_long, time_long, Ylong, Dlong))
    colnames(data_long) = c(varInd, varTime, varY, varD)
    # the first column is ind i, the second column is time t, 
    # the third column is outcome Y, the fourth column is treatment D
    return(data_long)
  } else{ # The panel includes covariates
    Ylong <- matrix(Y, nrow = TT*N, ncol = 1) # long panel for Y
    Dlong <- matrix(D, nrow = TT*N, ncol = 1) # long panel for D
    Xlong <- matrix(0, nrow = N*TT, ncol = length(varX))
    for (p in 1:length(varX)) {  
      Xlong[,p] <- matrix(X[[paste0("Xwide", p)]], nrow = TT*N, ncol = 1)  
    } # long panel for X
    
    time_long <- matrix(as.matrix(replicate(N,c(1:TT))), nrow = TT*N, ncol = 1)
    unit_long <- matrix(as.matrix(t(replicate(TT,c(1:N)))), nrow = TT*N, ncol = 1)
    
    data_long <- as.data.frame(cbind(unit_long, time_long, Ylong, Dlong, Xlong))
    colnames(data_long) = c(varInd, varTime, varY, varD, varX)
    # the first column is ind i, the second column is time t, 
    # the third column is outcome Y, the fourth column is treatment D, the rest are control variables X
    return(data_long)
  }
}

