#' @title matching.plot  
#'  
#' @description \code{matching.plot} visualize the match episode/cohort and create a grid plot.  
#'  
#' @param Dwide wide panel for treatment
#' @param c tuning parameter of carryover
#' @param a tuning parameter of pre-treatment
#' @param b tuning parameter of post-treatment
#' @param type "episode" or "cohort"
#' @param this_episode the chosen episode, will be used when type == "episode"
#' @param this_cohort the chosen cohort, will be used when type == "cohort"
#'  
#' @return \code{matching.plot} return a ggplot object of the chosen episode/cohort.
#' @author Hongyi Jiang <hyjiang2017@nsd.pku.edu.cn>  
#'  
#' @export 
matching.plot <- function(Dwide, c, a, b, type = "episode", this_episode, this_cohort = NULL){
  # Plot Function
  # Input: Dwide: T-N matrix of treatment status
  #        c: num. carryover periods
  #        a: num. pre-treatment periods
  #        b: num. post-treatment periods
  #        this_episode: episode information generated by match.R
  #        episode: full sets of episodes; can be omitted when plot_cohort = FALSE
  #        plot_cohort: Boolean, whether to plot a cohort or a single episode
  
  # library(ggplot2)
  
  # Matrix dimensions
  n_cols <- dim(Dwide)[1] # Number of periods, T
  n_rows <- dim(Dwide)[2] # Number of units, N
  
  if (type == "episode"){
    # Pre-treatment periods for this episode
    calender_times_pre = (as.numeric(this_episode$treated_time)-a):(as.numeric(this_episode$treated_time)-1)
    # Post-treatment periods for this episode
    calender_times_post = (as.numeric(this_episode$treated_time)):(as.numeric(this_episode$treated_time)+b)
    # Number of control units for this episode
    n_control = length(this_episode$control_units)
    # Specify colors for each cell
    group_data <- list(
      "1_Control: Post" = list(coords = data.frame(col = rep(calender_times_post,times=n_control), row = rep(as.numeric(this_episode$control_units),each=b+1)), color = "lightcoral"),
      "2_Control: Pre" = list(coords = data.frame(col = rep(calender_times_pre, times=n_control), row = rep(as.numeric(this_episode$control_units), each=a)), color = "lightblue"),
      "3_This Episode: Post" = list(coords = data.frame(col = calender_times_post, row = as.numeric(this_episode$treated_unit)), color = "darkred"),
      "4_This Episode: Pre" = list(coords = data.frame(col = calender_times_pre, row = as.numeric(this_episode$treated_unit)), color = "blue"),
      "5_Non-treated Obs" = list(coords = data.frame(which(t(Dwide)==0, arr.ind=TRUE)), color = "lightcyan"), # Non-treated units
      "6_Treated Obs" = list(coords = data.frame(which(t(Dwide)==1, arr.ind=TRUE)), color = "peachpuff")  # Treated units
    )
  }
  else if (type == "cohort"){
    # Pre-treatment periods for this cohort
    calender_times_pre = (as.numeric(this_cohort$treated_time)-a):(as.numeric(this_cohort$treated_time)-1)
    # Post-treatment periods for this cohort
    calender_times_post = (as.numeric(this_cohort$treated_time)):(as.numeric(this_cohort$treated_time)+b)
    # Number of control units for this cohort
    n_control = length(this_cohort$control_units)
    n_cohort = length(this_cohort$treated_units)
      group_data <- list(
        "1_Control: Post" = list(coords = data.frame(col = rep(calender_times_post,times=n_control), row = rep(as.numeric(this_cohort$control_units),each=b+1)), color = "lightcoral"),
        "2_Control: Pre" = list(coords = data.frame(col = rep(calender_times_pre, times=n_control), row = rep(as.numeric(this_cohort$control_units), each=a)), color = "lightblue"),
        "3_This Cohort: Post" = list(coords = data.frame(col = rep(calender_times_post, times=n_cohort), row = rep(as.numeric(this_cohort$treated_units), each=b+1)), color = "darkred"),
        "4_This Cohort: Pre" = list(coords = data.frame(col = rep(calender_times_pre, times=n_cohort), row = rep(as.numeric(this_cohort$treated_units), each=a)), color = "blue"),
        "5_Non-treated Obs" = list(coords = data.frame(which(t(Dwide)==0, arr.ind=TRUE)), color = "lightcyan"), # Non-treated units
        "6_Treated Obs" = list(coords = data.frame(which(t(Dwide)==1, arr.ind=TRUE)), color = "peachpuff")  # Treated units
      )    
  } else {
      stop("The match type only contains episode or cohort.")
    }
  
  # Extract all coordinates and assign group labels
  all_coords <- do.call(rbind, lapply(names(group_data), function(group) {
    coords <- group_data[[group]]$coords
    coords$group <- group
    return(coords)
  }))
  colnames(all_coords) <- c("x", "y", "group")
  all_coords <- all_coords[order(all_coords$x, all_coords$y, all_coords$group),]
  # Ensure priority by removing duplicates, keeping the first match
  all_coords <- all_coords[!duplicated(paste(all_coords$x, all_coords$y)), ]
  
  # Create a complete grid for the matrix
  grid <- expand.grid(x = 1:n_cols, y = 1:n_rows)
  
  # Merge with all_coords to assign groups
  grid <- merge(grid, all_coords, by = c("x", "y"), all.x = TRUE)
  grid$group[is.na(grid$group)] <- "Empty"  # Assign "Empty" to unfilled cells
  
  # Define color palette including "Empty"
  group_colors <- sapply(group_data, function(g) g$color)
  group_colors["Empty"] <- "#EAEAEA"  # Light gray for empty cells
  
  # title
  if (type == "episode"){
    title = paste0("Treated Unit=", this_episode$treated_unit, ", Treated Time=", this_episode$treated_time , "\nNum. Pre-periods=", a, ", Num. Post Period=", b, ", Num. Carryover=", c)
  }
  else if (type == "cohort"){
    title = paste0("Treated Cohort=", this_cohort$treated_time , "\nNum. Pre-periods=", a, ", Num. Post Period=", b, ", Num. Carryover=", c)
  }
  
  # Plot using ggplot2
  p <- ggplot(grid, aes(x = !!sym("x"), y = !!sym("y")))
  p <- p +
    geom_tile(aes(fill = !!sym("group")), color = NA) +  # Use pre-specified colors
    scale_fill_manual(values = group_colors, name = "Group") +
    scale_y_continuous(
      trans = "reverse"
    ) +
    scale_x_continuous(
      breaks = 1:n_cols,
      labels = 1:n_cols
    ) +
    theme_minimal() +
    theme(
      axis.title = element_blank(),
      axis.text.x = element_text(size = 10),
      axis.text.y = element_text(size = 10),
      axis.ticks = element_line(),
      panel.grid = element_blank(),  # Remove background grid
      panel.background = element_blank()  # Ensure no background color
    ) +
    coord_fixed(ratio = n_cols / n_rows / ((1 + sqrt(5)) / 2)) +  # Adjust for golden ratio
    ggtitle(title) +
    theme(plot.title = element_text(size = 10)) # Adjust the size as needed
    return(p)
}